const squares = [
    "Double Manus",
    "Tree on ledge in Anor Londo",
    "Gwyn at bottom of Blighttown",
    "Toad blocking a doorway",
    "Big hat",
    "Carving used the cross Crystal Cave",
    "Three pants in a row",
    "Boss replaced by regular enemy",
    "Dies in lava",
    "Cheeses boss fight off a cliff",
    "Ninja flip ring",
    "Falls to death in Ash Lake",
    "Falls to death in Blighttown",
    "Pig blocking a doorway",
    "Boss pops out of crate or barrel",
    "C-Cursed!?",
    "Uses black knight weapon",
    "T-posing boss",
    "Softlock in Moonlight Butterfly",
    "Barb forgets an item from the zone he just left",
    "Boss in Firelink Shrine",
    "Binoculars on Gwynevere",
    "Centipede Demon kills Barb through a wall",
    "First try Avelyn chest",
    "Dish washing gloves",
    "Man, these DLC enemies suck",
    "Catarina helm",
    "Game crash"
]